//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drastic.YouTube.Explorer.Translations {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Drastic.YouTube.Explorer.Translations.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Drastic.YouTube.Explorer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Author:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AuthorHeader {
            get {
                return ResourceManager.GetString("AuthorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Average Rating:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AverageRatingHeader {
            get {
                return ResourceManager.GetString("AverageRatingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Chapters: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChaptersHeader {
            get {
                return ResourceManager.GetString("ChaptersHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Description に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DescriptionHeader {
            get {
                return ResourceManager.GetString("DescriptionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Total Dislikes: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DislikeCountHeader {
            get {
                return ResourceManager.GetString("DislikeCountHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Duration: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DurationHeader {
            get {
                return ResourceManager.GetString("DurationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Total Likes: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LikeCountHeader {
            get {
                return ResourceManager.GetString("LikeCountHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loading Metadata... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoadingMetadata {
            get {
                return ResourceManager.GetString("LoadingMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Browser に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenBrowserText {
            get {
                return ResourceManager.GetString("OpenBrowserText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Share に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShareButtonText {
            get {
                return ResourceManager.GetString("ShareButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartHeader {
            get {
                return ResourceManager.GetString("StartHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stats に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StatsHeader {
            get {
                return ResourceManager.GetString("StatsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Thumbnails に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ThumbnailHeader {
            get {
                return ResourceManager.GetString("ThumbnailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Title:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TitlesHeader {
            get {
                return ResourceManager.GetString("TitlesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Views:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewsHeader {
            get {
                return ResourceManager.GetString("ViewsHeader", resourceCulture);
            }
        }
    }
}
